class GameJamConstants {
  static const title = 'The Pixelated Toast Game Jam 2';
  static const subtitle1 = 'Wat is een game jam?';
  static const textBlock1 =
      'Een game jam is een soort van hackathon in het genre van game development. Het doel van het evenement is om als team of individueel op een korte periode een game te ontwikkelen. Elke game jam heeft zijn eigen specifieke thema en regels waar de deelnemers zich aan moeten houden. Het thema van de jam wordt altijd bekend gemaakt aan de start van het evenement. De ontwikkelaars mogen zelf kiezen hoe ze het thema interpreteren en hun brede fantasie gebruiken om dit uit te werken. Na de afloop van de jam worden de ingestuurde resultaten beoordeeld en wordt er een winnaar verkozen.';
  static const textBlock2 =
      'The Pixelated Toast Game Jam 2 is de tweede editie van een game jam die georganiseerd werd door Odiwa. De deelnemers hadden 24 uur de tijd om een game uit te werken binnen het thema ‘Every Ending is a New Beginning’.  Eén van de belangrijkste regels was dat de game art zelf gemaakt moest worden met Pixel Art. De jam werd georganiseerd van 22 oktober 2022 om 6 uur tot 23 oktober 2022 om 6 uur op de website Itch.io. Dit is een bekende site voor onafhankelijke game developers om hun games te uploaden (eventueel met een verkoopprijs), om mee te doen aan online game jams, anderen hun games te spelen en meer. Meer info over deze game jam is te vinden op https://itch.io/jam/pixelated-toast-jam-2.';
  static const subtitle2 = 'Hoe begin ik hieraan?';
  static const textBlock3 =
      'Het begin van een game jam is meestal het moeilijkste deel. Voor ik kon beginnen met ontwikkelen waren er een paar belangrijke aspecten waar ik goed over moest nadenken. Wat is het doel van mijn game? Welk genre heeft de game? Hoe is de game gelinkt aan het thema? Welke technieken kan de speler gebruiken? Welke tools gebruik ik om de game te maken? Om deze vragen te beantwoorden heb ik eerst even de tijd genomen om een planning op te maken en voor mezelf uit te zoeken wat ik allemaal wou realiseren binnen deze korte tijd.';
  static const subtitle3 = 'Het idee';
  static const textBlock4 =
      'Na wat brainstormen en wat ideeën te overlopen ben ik tot een besluit gekomen en wist ik genoeg om te starten met de ontwikkeling. Mijn idee was om een dungeon shooter game te maken waarbij de speler zo lang mogelijk moet proberen overleven. In de dungeon spawnen monsters op willekeurige plaatsen en de speler moet deze monsters proberen te ontwijken en doden met een geweer. Wanneer de speler gevangen wordt door een monster verliest hij een leven en spawnt hij terug op een veilige plaats. De game gaat zo oneindig door tot de speler geen levens meer heeft en de moeilijkheidsgraad van het spel gaat geleidelijk omhoog hoe langer de speler in leven blijft.';
  static const textBlock5 =
      'Om binnen het thema ‘Every Ending is a New Beginning’ te blijven wou ik iets laten gebeuren met het hoofdpersonage nadat hij sterft en een leven verliest. Het hoofdpersonage is een stukje toast dat opgegeten kan worden door de monsters. Wanneer hij sterft zal er een nieuw stuk toast gemaakt worden door de broodrooster en gaat de game verder met dit stukje toast. Zo is het einde van het ene krokante personage het begin van een andere.';
  static const subtitle4 = 'De uitwerking';
  static const textBlock6 =
      'Nu ik wist wat mijn doel was kon ik beginnen aan de ontwikkeling. Ik maak mijn games altijd met de Unity game engine en C# als programmeertaal. Het eerste wat ik dus gedaan heb is een nieuw Unity project opzetten. Eens het project geladen was, ben ik onmiddellijk gestart met het maken van de omgeving waarin de game plaatsvindt, de dungeon dus. De omgeving wordt gemaakt met een tileset. Dit zijn allemaal tegels die op een rooster geplaatst worden om bijvoorbeeld een muur te bouwen. Ik heb de tegels getekend in het Pixel Art programma Piskel. Dit is een gratis programma dat relatief eenvoudig is.';
  static const textBlock7 =
      'Na het maken van de omgeving heb ik een simpele toast speler getekend die kon rondwandelen in de dungeon. Deze speler moest natuurlijk ook een wapen hebben dus heb ik een geweer geprogrammeerd dat half-automatisch kogels afschiet. De kogels wijken telkens lichtjes af om het spel realistischer en interessanter te maken. Deze kogels hebben natuurlijk geen nut als er niets is om op te schieten. Daarom moesten er monsters komen als vijanden die de speler achtervolgen. Ik ben begonnen met 1 monster te implementeren omdat ik eerst alle noodzakelijke features wou afmaken en daarna extra’s toevoegen.';
  static const textBlock8 =
      'Nadat de speler kon bewegen en schieten op monsters die hem achtervolgen, ontbrak er nog een belangrijk onderdeel en dat was de gameplay-loop. Hiervoor heb ik een broodrooster getekend die een nieuwe speler maakt telkens er een toastje sterft. Na nog wat simpele UI-elementen toe te voegen zodat de speler zijn tijd en levens kon zien, was het belangrijkste van de game af en had ik al een werkend product.';
  static const textBlock9 =
      'Er waren nog enkele uren te gaan voor het einde van de game jam en ik was nog niet moe. Daarom besloot om de game nog wat te verbeteren. Om de game wat toffer en interessanter te maken wou ik de monsters een betere techniek geven om de speler te volgen dan gewoon in een rechte lijn er naartoe lopen. Hiervoor heb ik een AI-package gebruikt die de kortste route naar de speler berekent en rekening houdt met muren en obstakels. Als tweede toevoeging heb ik nog 2 extra monsters gecreëerd om meer variatie in het spel te brengen. Met deze toevoegingen was de game klaar en heb ik hem op tijd ingediend op Itch.io.';
  static const subtitle5 = 'Het resultaat';
  static const textBlock10 =
      'Na een lange dag van bijna 24 uur ben ik toch tot een mooi resultaat gekomen. De game kan gespeeld worden op Itch.io of je kan hem downloaden voor Windows via deze link: https://dennidev.itch.io/get-toasted.';
  static const subtitle6 = 'Reflectie';
  static const textBlock11 =
      'Ik heb deze activiteit gekozen voor mijn portfolio omdat dit een zeer unieke en toffe ervaring was. Op papier klinkt dit als een duidelijke opdracht, maak een game. In realiteit komt er veel meer bij kijken dan je op het eerste gezicht zou denken. Het is niet zo zeer dat ik veel technische skills heb bijgeleerd maar ik werd wel geconfronteerd met planning, scope management en tijdsdruk.';
  static const textBlock12 =
      'Het was zeer belangrijk dat ik niet te snel met de opdracht gestart ben en eerst even de tijd heb genomen om te plannen en na te denken over wat ik allemaal wou bereiken. Dit is een advies dat ik al van verschillende developers heb gehoord en nu ervaar ik zelf het effect ervan. Ik ben blij dat ik hier de tijd voor heb genomen. Door te plannen had ik tijdens het ontwikkelen een goed beeld van wat ik nog allemaal moest doen en kon ik ook veel beter inschatten of ik op tijd klaar zou geraken.';
  static const textBlock13 =
      'Scope management is ook een zeer belangrijk en moeilijk onderdeel binnen development en zeker binnen game development. De scope van de game moest goed ingeschat worden omdat dit bepaalt of de game af zal geraken binnen de tijd of niet. Als je een te grote scope hebt, zal de game nooit op tijd af zijn. Omdat dit mijn eerste game jam was, heb ik de scope niet te groot gelegd zodat ik zeker binnen de tijd klaar zou geraken. Dit is goed gelukt want op het einde had ik nog een beetje tijd over om wat extra features te implementeren.';
  static const textBlock14 =
      'Omdat de game jam maar 24 uur duurde was er een grote tijdsdruk. Door deze druk heb ik tijdens het ontwikkelen belangrijke beslissingen moeten nemen over hoe ik mijn tijd verdeel. Ik heb mezelf moeten weerhouden van kleine details en eerst alle belangrijke features geïmplementeerd om een werkend product te bekomen.';
  static const textBlock15 =
      'Ik heb tijdens deze game jam dus leren omgaan met planning, scope management, tijdsdruk en mijn doorzettingsvermogen werd getest. Dit zijn allemaal zeer nuttige skills die me ongetwijfeld nog gaan helpen in de toekomst in het werkveld. Technische skills zoals programmeren zijn makkelijker aan te leren. Deze skills moet je echt ervaren om ze te ontwikkelen en daarom was deze game jam een zeer nuttige, leerrijke ervaring.';
}
